version: '3.3'

services:
  node:
    build: ./docker/app
    volumes:
      - ./app    
    depends_on: 
      - mysql
    environment: 
      - DATABASE_HOST=mysql

    entrypoint: "node app.js"
    tty: true

  mysql:
    build: ./docker/mysql
    volumes:
      - ./data/mysql/:/var/lib/mysql
    expose:
      - "3306"